### ISSUE TITLE
Next Upload counter doesn't work

### ISSUE THREAD

**Issue by rokssolana** [HabitRPG/habitrpg-chrome#120]
When the Next Upload counter reaches zero, it starts counting forward not backwards. I have uploads set for every 7 minutes, and it is already at 41 minutes and counting forwards, and no uploads for all this time.

**Comment by paglias** [comment]
@rokssolana sorry about this! we thought it was fixed but it's not, I've been able to reproduce.

**Comment by rokssolana** [comment]
There's a workaround, you can disable and then re-enable the extension and
then the counter works good for a while, but it would be better if there
was no bug.

**Comment by paglias** [comment]
I'm trying to reproduce the exact moment when it stops working, if you have some more information then it would be great

**Comment by paglias** [comment]
@rokssolana I found it! I've just published an update to fix this issue but it'll take at least 60m and may require you to restart chrome to get the updated version. Let me know if it works correctly

**Comment by rokssolana** [comment]
Hey, I hate to tell you but the bug still persists :( Although I have
restarted the browser a couple of times since. I think I figured out when
it breaks — it's if you stay at the same page for a long time, for example,
if I read a long article at Instapaper or write a paper in Google Docs.

**Comment by paglias** [comment]
@rokssolana could you do me a favour? You should right click on the extension icon, go to Manage Extensions and check that the version number next to the extension name is "2.4"

**Comment by rokssolana** [comment]
It is indeed 2.4, not some old version, unfortunately.

**Comment by paglias** [comment]
@rokssolana I'm trying to reproduce what you're experiencing but I need some more info:

1. It happens only when staying on the same page for a long time?
2. What are your settings? I mean the site watcher is set up to stay active always or just on certain hours/days? If the latter, could you give me your settings? Like every day from 7am to 9pm, excpet weekends...

Thanks

**Comment by rokssolana** [comment]
1. Looks like that, but I'm not 100% sure. It seems to me that now it
happens less often than before your last fix. But it happened like three
times since then.
2. It is always active.

**Comment by aroonk** [comment]
I signed up yesterday, and just want to confirm I've been having this problem too. The browser monitoring is the key part of how I'll be using HabitRPG, so hope there's a fix soon!

Using HabitRPG 2.4, Chrome 41.0.2272.89, OS X 10.9.5.

**Comment by zzx908** [comment]
I've also been experiencing this problem, it is only when I go in "options" and click "save" that the counter gets back to work

**Comment by Kixunil** [comment]
Happened to me too. The numbers were negative for a while.

**Comment by theredmanor** [comment]
I also experience this problem. This plugin was the only reason I moved to Chrome :(
